### ISSUE TITLE
v5.0 CheeseSquare won't compile if Packages version == 22.2

### ISSUE THREAD

**Issue by makerofthings7** [xamarin/monodroid-samples#88] opened 2015-07-23 04:07 UTC
Issue with MainActivity line 86
   navigationView.NavigationItemSelected += (sender, e) => {
				e.MenuItem.SetChecked (true); //.P0.SetChecked (true);
                drawerLayout.CloseDrawers ();
            };

Issue with "Activity not deriving from theme"

**Comment by abhisheks360** [comment] 2016-06-29 11:53
Thanks for Reported this issue. I am unable to reproduce this issue I checked updated sample now it is working fine at my end. here is the screencast:http://www.screencast.com/t/akR1YMbFF

Hence I closing this issue.
Thanks!

**Closed** 2016-06-29 17:50 UTC
