### ISSUE TITLE
CalendarDemo

### ISSUE THREAD

**Issue by BobVal** [xamarin/monodroid-samples#44] opened 2013-09-18 21:27 UTC
I downloaded, compiled and installed the CalendarDemo on my Android and when I run the program and look at the Events I have in my calendars all the Event Days are off my 1. 

One of the Events is Dec 6th 2013 and it shows it as Dec 5th 2013
Another is Jan 28th 2014 and it shows it as Jan 27th 2014.

Looking at the code I have to assume that  ".dtstart" is not being read right?

Is this a problem I can fix?

BobVal

**Comment by abhisheks360** [comment] 2016-06-29 16:16
Thanks for Reported this issue. I am unable to reproduce this issue I checked updated sample now it is working fine at my end. 
Hence I closing this issue.
Thanks!

**Closed** 2016-06-29 17:58 UTC
