### ISSUE TITLE
Missing precompiled 4.4.0 jar?

### ISSUE THREAD

**Issue by brianchance** [xamarin/monodroid-samples#38] opened 2013-08-21 20:13 UTC
I am having a problem replacing my 4.2.0 version with the 4.4.0 component version and was hoping to update from here.

Shouldn't the update to 4.4.0 have a new jar file (ActionBarSherlock-4.4.0.zip)?

**Comment by abhisheks360** [comment] 2016-06-29 14:34
Thanks for Reported this issue. I am unable to reproduce this issue I checked updated sample now it is working fine at my end. here is the screencast: http://www.screencast.com/t/B8pPqPhZ0

Hence I closing this issue.
Thanks!

**Closed** 2016-06-29 17:55 UTC
