### ISSUE TITLE
Exception with Google Play service reference 

### ISSUE THREAD

**Issue by KathirveluM** [xamarin/monodroid-samples#101] opened 2015-11-11 14:24 UTC
Hi, We are facing an issue while trying to add the Xamarin.GooglePlayservices.Location.dll in geofence sample project mentioned in the below link.
https://github.com/xamarin/monodroid-samples/tree/master/google-services/Location/Geofencing 

When we build the project , showing the below error message for Location Services dll. 

error: package com.google.android.gms.maps.StreetViewPanorama does not exist
        com.google.android.gms.maps.StreetViewPanorama.OnStreetViewPanoramaLongClickListener

error: package com.google.android.gms.maps.StreetViewPanorama does not exist
        com.google.android.gms.maps.StreetViewPanorama.OnStreetViewPanoramaClickListener

 error: package com.google.android.gms.maps.StreetViewPanorama does not exist
        com.google.android.gms.maps.StreetViewPanorama.OnStreetViewPanoramaChangeListener

error: package com.google.android.gms.maps.StreetViewPanorama does not exist
        com.google.android.gms.maps.StreetViewPanorama.OnStreetViewPanoramaCameraChangeListener

error: package com.google.android.gms.maps.model does not exist
    public void onStreetViewPanoramaLongClick (com.google.android.gms.maps.model.StreetViewPanoramaOrientation p0)

 error: package com.google.android.gms.maps.model does not exist
    public void onStreetViewPanoramaClick (com.google.android.gms.maps.model.StreetViewPanoramaOrientation p0)

 error: package com.google.android.gms.maps.model does not exist
    public void onStreetViewPanoramaChange (com.google.android.gms.maps.model.StreetViewPanoramaLocation p0)

package com.google.android.gms.maps.model does not exist
    public void onStreetViewPanoramaCameraChange (com.google.android.gms.maps.model.StreetViewPanoramaCamera p0)

 error: package com.google.android.gms.maps.model does not exist
    public void onMarkerDragStart (com.google.android.gms.maps.model.Marker p0)

 error: package com.google.android.gms.maps.model does not exist
    public void onMarkerDragEnd (com.google.android.gms.maps.model.Marker p0)

 error: package com.google.android.gms.maps.model does not exist
    public void onMarkerDrag (com.google.android.gms.maps.model.Marker p0)

 error: package com.google.android.gms.maps.model does not exist
    public void onMapLongClick (com.google.android.gms.maps.model.LatLng p0)

error: package com.google.android.gms.maps.model does not exist
    public void onMapClick (com.google.android.gms.maps.model.LatLng p0)
 error: package com.google.android.gms.maps.model does not exist
    public void onInfoWindowClick 
 error: package com.google.android.gms.maps.model does not exist
    public void onIndoorLevelActivated 
error: package com.google.android.gms.maps.model does not exist
    public void onCameraChange (com.google.android.gms.maps.model.CameraPosition p0)

error: package com.google.android.gms.maps.model does not exist
    public boolean onMarkerClick (com.google.android.gms.maps.model.Marker p0)

error: package com.google.android.gms.maps.model does not exist
    private native void n_onStreetViewPanoramaLongClick (com.google.android.gms.maps.model.StreetViewPanoramaOrientation p0);

 error: package com.google.android.gms.maps.model does not exist
    private native void n_onStreetViewPanoramaClick (com.google.android.gms.maps.model.StreetViewPanoramaOrientation p0);

 error: package com.google.android.gms.maps.model does not exist
    private native void n_onStreetViewPanoramaChange (com.google.android.gms.maps.model.StreetViewPanoramaLocation p0);

 error: package com.google.android.gms.maps.model does not exist
    private native void n_onStreetViewPanoramaCameraChange (com.google.android.gms.maps.model.StreetViewPanoramaCamera p0);

 error: package com.google.android.gms.maps.model does not exist
    private native void n_onMarkerDragStart (com.google.android.gms.maps.model.Marker p0);

 error: package com.google.android.gms.maps.model does not exist
    private native void n_onMarkerDragEnd (com.google.android.gms.maps.model.Marker p0);

 error: package com.google.android.gms.maps.model does not exist
    private native void n_onMarkerDrag (com.google.android.gms.maps.model.Marker p0);

 error: package com.google.android.gms.maps.model does not exist
    private native void n_onMapLongClick (com.google.android.gms.maps.model.LatLng p0);

 error: package com.google.android.gms.maps.model does not exist
    private native void n_onMapClick (com.google.android.gms.maps.model.LatLng p0);

 error: package com.google.android.gms.maps.model does not exist
    private native void n_onInfoWindowClick (com.google.android.gms.maps.model.Marker p0);

 error: package com.google.android.gms.maps.model does not exist
    private native void n_onIndoorLevelActivated (com.google.android.gms.maps.model.IndoorBuilding p0);

 error: package com.google.android.gms.maps.model does not exist
    private native void n_onCameraChange (com.google.android.gms.maps.model.CameraPosition p0);

 error: package com.google.android.gms.maps.model does not exist
    private native boolean n_onMarkerClick (com.google.android.gms.maps.model.Marker p0);

 error: package com.google.android.gms.maps.LocationSource does not exist
        com.google.android.gms.maps.LocationSource.OnLocationChangedListener

error: package com.google.android.gms.maps.GoogleMap does not exist
        com.google.android.gms.maps.GoogleMap.OnMyLocationChangeListener

 error: package com.google.android.gms.maps.GoogleMap does not exist
        com.google.android.gms.maps.GoogleMap.OnMyLocationButtonClickListener

 error: package com.google.android.gms.maps.GoogleMap does not exist
        com.google.android.gms.maps.GoogleMap.OnMarkerDragListener

 error: package com.google.android.gms.maps.GoogleMap does not exist
        com.google.android.gms.maps.GoogleMap.OnMarkerClickListener

 error: package com.google.android.gms.maps.GoogleMap does not exist
        com.google.android.gms.maps.GoogleMap.OnMapLongClickListener

 error: package com.google.android.gms.maps.GoogleMap does not exist
        com.google.android.gms.maps.GoogleMap.OnMapClickListener

 error: package com.google.android.gms.maps.GoogleMap does not exist
        com.google.android.gms.maps.GoogleMap.OnInfoWindowClickListener

 error: package com.google.android.gms.maps.GoogleMap does not exist
        com.google.android.gms.maps.GoogleMap.OnIndoorStateChangeListener

 error: package com.google.android.gms.maps.GoogleMap does not exist
        com.google.android.gms.maps.GoogleMap.OnCameraChangeListener

**Comment by abhisheks360** [comment] 2016-06-28 14:29
Thanks for Reporting this issue.I am unable to reproduce this issue.I checked this updated sample and now it is working fine for my end. http://www.screencast.com/t/nMWuNB2ce.
Hence I closing this issue.
Thanks!

**Closed** 2016-06-28 17:39 UTC
