### ISSUE TITLE
ActionBarPullToRefresh doesn't build with ActionBarSherlock 4.4.0

### ISSUE THREAD

**Issue by chrisriesgo** [xamarin/monodroid-samples#47] opened 2013-10-23 15:05 UTC
I blindly tried adding the ActionBarPullToRefresh.dll to my existing project that uses ActionBarSherlock, and started seeing build errors like the following:

`package uk.co.senab.actionbarpulltorefresh.library.PullToRefreshAttacher does not exist uk.co.senab.actionbarpulltorefresh.library.PullToRefreshAttacher.OnRefreshListener`

The ActionBarPullToRefresh sample app worked fine, so I was confused. I added a reference to ActionBarSherlock (and then Mono.Android.Support.v4), and then the sample project started having build errors:

    package com.actionbarsherlock.widget.ShareActionProvider does not exist com.actionbarsherlock.widget.ShareActionProvider.OnShareTargetSelectedListener
    package com.actionbarsherlock.widget.SearchView does not exist com.actionbarsherlock.widget.SearchView.OnSuggestionListener 
    etc...

Double-clicking the error opens up one of the generated obj/.../*.java files.

Is ActionBarPullToRefresh not compatible with ActionBarSherlock? Can it be made to be if not?

**Comment by abhisheks360** [comment] 2016-06-29 12:11
Thanks for Reported this issue. I am unable to reproduce this issue I checked updated sample now it is working fine at my end. here is the screencast:http://www.screencast.com/t/igus7yjZXg

Hence I closing this issue.
Thanks!

**Closed** 2016-06-29 17:48 UTC
